### ISSUE TITLE
AXTree view is broken on recent Chromium builds

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [MicrosoftEdge/JsDbg#11]
This is due to the Chromium changes that introduced AXTreeManager.

**Comment by sanketj** [comment]
When you complete the PR, I think it will give you an option to close this issue. If not, you can close it manually after.

**Comment by KurtCattiSchmidt** [comment]
Resolved with PR https://github.com/MicrosoftEdge/JsDbg/pull/12
