### ISSUE TITLE
JsDbg Visual Studio (VS) 2019 extension support

### ISSUE THREAD

**Issue by SamFort-MSFT** [MicrosoftEdge/JsDbg#120]
Consider adding support for VS 2019 to the Visual Studio extension version

**Comment by sanketj** [comment]
Thanks for reporting this! We should definitely add support for VS 2019. Let me do some initial investigations to see what this would take.

**Comment by sanketj** [comment]
@SamFort-MSFT - #123 should enable this. Once that's merged in, I'll deploy the new vsix for download.

**Comment by sanketj** [comment]
@SamFort-MSFT I have deployed the vsix that works with VS 2019. Feel free to download and try it out. Let me know if you encounter any issues.

**Comment by SamFort-MSFT** [comment]
It installs now but I get this error when it tries to load.

    <record>2457</record>
    <time>2019/05/23 00:57:20.350</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [JsDbgPackage]Source: &apos;JsDbg.VisualStudio&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at JsDbg.VisualStudio.AutoUpdater.CheckForUpdates(String identifier, String updateUrl)&#x000D;&#x000A;   at JsDbg.VisualStudio.JsDbgPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{5B3AF206-B4D4-4D12-9661-5D2D8DD8D194}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
