### ISSUE TITLE
Suggestion: About/Help should show where JSDbg is installed

### ISSUE THREAD

**Issue by sushraja-msft** [MicrosoftEdge/JsDbg#14]
I was trying to write and extension today after installing jsdbg for visual studio. I had to search my c: to find the install location of jsdb since the extension installer auto picks the place to install jsdbg.

C:\Users\(user-name)\AppData\Local\Microsoft\VisualStudio\15.0_84d86a5b\Extensions\wngg5enl.eby\extensions\examples

was where it was installed.

**Comment by petersalas** [comment]
Out of curiosity -- did the "Extensions" extension not work?  Or was it not obvious that that was the way to load/author new extensions?

**Comment by sanketj** [comment]
Yes, the "All Loaded Extensions" pane in the "Extensions" extension should show you the path for every extension.

**Comment by cbiesinger** [comment]
And you can also point it to a JSDbg checkout's extension directory there.

But maybe it would be good to mention that in CONTRIBUTING.md, it took me a while to find that as well.

**Comment by sanketj** [comment]
Yes, documentation on that is definitely missing. Filing a separate issue for that.
