### ISSUE TITLE
[gdb] Support 'typename' parameter to LookupGlobalSymbol or equivalent

### ISSUE THREAD

**Issue by cbiesinger** [MicrosoftEdge/JsDbg#54]
The typename is used to disambiguate global symbols and is used in ax-tree.js which is trying to access a function-local variable named "instance" (https://cs.chromium.org/chromium/src/ui/accessibility/ax_tree_manager_map.cc?sq=package:chromium&g=0&l=13):
```cc
namespace ui {
[...]
AXTreeManagerMap& AXTreeManagerMap::GetInstance() {
  static base::NoDestructor<AXTreeManagerMap> instance;
```

On Windows, "instance" gets looked up without qualifier and is thus ambiguous, and gets disambiguated by type.

On GDB, it could get looked up like this:
```
(gdb) p 'ui::AXTreeManagerMap::GetInstance()'::instance
$1 = {
  storage_ = '\000' <repeats 39 times>
}
```

Need to figure out how to best implement this. Perhaps re-purposing the namespace argument wouldn't be too bad? Or else need to find a way to iterate over global symbols and match them by type.

**Comment by cbiesinger** [comment]
Also:
>>> gdb.lookup_symbol('ui::AXTreeManagerMap::GetInstance()::instance')
(<gdb.Symbol object at 0x7fca45d5fb98>, False)

**Comment by sanketj** [comment]
Interesting...

Looks like GDB accepts more than just namespaces as prefixes for global symbols. Perhaps we should rename the namespace parameter? Also, if the typename parameter is not useful to GDB, perhaps it can ignore it in the same way WinDbg/VS ignores the namespace parameter?

**Comment by sanketj** [comment]
@KurtCattiSchmidt Just FYI...

**Comment by cbiesinger** [comment]
For my reference, some notes in testing in https://github.com/MicrosoftEdge/JsDbg/pull/29#discussion_r279016745

**Comment by cbiesinger** [comment]
Fixed by https://github.com/MicrosoftEdge/JsDbg/pull/58

Note, the AX Tree extension does not quite work yet because we do not yet support std::__Cr::unordered_map
